[metadata]
name = turborest
version = 0.1.1
description = A library for monitoring files and directories for changes
long_description = file: README.md
long_description_content_type = text/markdown
author = ByteSentinel.io
author_email = dev@bytesentinel.io
url = https://github.com/bytesentinel-io/turborest
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    =src
packages = find:
include_package_data = True
python_requires = >=3.7

[options.packages.find]
where = src